import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as Sonner } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import Navbar from "@/components/layouts/nav-bar/navbar";
import Providers from "@/redux/Provider";
import { createClient } from "@supabase/supabase-js";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora",
});

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createSupabaseServerClient();
  const { data, error } = await supabase.auth.getUser();
  if (error || !data?.user) {
    redirect("/auth/login");
  }
  console.log(data);
  const supabase2 = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY!
  );
  const result: any = !error
    ? await supabase2
        .from("employees")
        .select(
          `
        id,
        email,
        first_name,
        last_name,
        image_url,
        address,
        contact_number,
        roles (id, role),
        created_at,
        password
      `
        )
        .eq("id", data.user.id)
    : null;

  return (
    <html lang="en">
      <Providers>
        <body className={cn("font-sora", sora.variable)}>
          <div className="w-full min-h-screen hidden bg-stone-900/10 max-lg:flex justify-center place-items-center">
            <h1 className="text-3xl text-slate-900 font-semibold">
              Please use a larger screen to view this page{" "}
            </h1>
          </div>

          <div className="relative flex place-items-start justify-center w-full min-h-screen h-screen bg-darkBg px-8 gap-10 max-lg:hidden overflow-y-scroll overflow-x-hidden no-scrollbar">
            <Navbar data={result.data[0]} />
            {children}
          </div>
          <Sonner />
          <Toaster />
        </body>
      </Providers>
    </html>
  );
}
